[build-system]
requires = []
build-backend = "setuptools.build_meta"
backend-path = ["."]

[tool.black]
skip-string-normalization = true

[tool.setuptools_scm]

[tool.pytest-enabler.black]
# disabled

[tool.pytest-enabler.mypy]
# disabled
